strategy:
  class: TopkDropoutStrategy
  module_path: qlib.contrib.strategy
  kwargs:
    signal: <PRED>
    topk: 50
    n_drop: 5

backtest:
  start_time: "2022-01-01"
  end_time: "2024-12-31"
  account: 100000000
  benchmark: SH000300
  exchange_kwargs:
    freq: day
    limit_threshold: 0.095
    deal_price: close
    open_cost: 0.0005
    close_cost: 0.0015
    min_cost: 5
